config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  post 'calendar/create'

  resources :reservations
  resources :contacts

  resources :home, only: :index do
    collection { get :photos }
  end
end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
  serialize :available_dates, Array

  after_validation :set_refresh_date

  class << self
    def check_availability(arrival, depart)
      VRBO::Calendar.new.available?(arrival, depart, latest.try(:available_dates))
    end

    def outdated?
      latest_record = latest
      !latest_record || latest_record.available_dates.blank? || latest_record.refresh_date < 45.minutes.ago
    end

    def latest
      order('id DESC').first
    end
  end

  private

  def set_refresh_date
    self.refresh_date = Time.now
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessor :device_type
  validates :email, :format => {:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create}
  validates :name, :arrival_date, :departure_date, presence: true
  validate :valid_arrival
  validate :spam

  def message_for_email
    if message.present?
      message.strip.chomp
    else
      'Not provided.'
    end
  end

  def valid_arrival
    if arrival_date && arrival_date < Date.today
      errors.add(:arrival_date, "should be in the future")
    end
  end

  def spam
    if device_type.present?
      errors.add(:base, "Bug off")
    end
  end
end

app/models/date_range.rb
class DateRange
  attr_reader :start_at, :end_at, :errors

  class << self
    def convert(the_date)
      the_date.gsub(%r{(\d{2})/(\d{2})/(\d+)}, '\3-\1-\2')
    end
  end

  def initialize(start_at=nil, end_at=nil)
    @start_at = start_at
    @end_at = end_at
    @errors = []
  end

  def to_date!
    convert!
    @start_at = Date.parse(start_at) rescue nil
    @end_at = Date.parse(end_at) rescue nil
  end

  def convert!
    @start_at = convert(start_at)
    @end_at = convert(end_at)
  end

  def convert(the_date)
    self.class.convert(the_date)
  end

  def validate
    @errors = []
    if !start_at
      errors << 'Please enter an arrival date'
    elsif !end_at
      errors << 'Please enter a departure date'
    elsif start_at > end_at
      errors << 'Departure date should be later than arrival date'
    elsif start_at < Date.today
      errors << 'You should really plan for a trip in the future instead of the past'
    end
  end

  def valid?
    validate
    errors.blank?
  end

  def open?
    true # Calendar.check_availability(start_at, end_at)
  end

  def diff_days
    (end_at - start_at).to_i
  end

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from ActionController::RoutingError, with: :go_home

  private

  def go_home
    redirect_to root_path
  end
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def create
    date_range = DateRange.new(params[:arrival_date], params[:departure_date])
    date_range.to_date!

    if date_range.valid?
      if Calendar.outdated?
        Calendar.create(available_dates: VRBO::Calendar.new.available_dates)
      end
      render json: date_range.open?, status: :ok
    else
      render json: date_range.errors.first, status: :unprocessable_entity
    end

  rescue
    render json: 'Oops! Something went wrong', status: :internal_server_error
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    # @contact instantiated in the HomeController instead
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.departure_date = DateRange.convert(contact_params[:departure_date])
    @contact.arrival_date = DateRange.convert(contact_params[:arrival_date])

    if @contact.save
      Inquiry.new_inquiry(@contact).deliver_now
      render json: nil, status: :created
    else
      render json: @contact.errors, status: :unprocessable_entity
    end
  end

  protected

  def contact_params
    @_contact_params ||= params.require(:contact).permit!
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @contact = Contact.new(number_of_people: 2)
    @calendar = Calendar.latest || Calendar.new
    @calendar.available_dates.keep_if { |date| Date.parse(date) >= current_date }
    # @availability = VRBO::Availability.new @calendar.available_dates
  end

  def photos
    render partial: 'photos'
  end

  private

  def current_date
    @current_date ||= Date.current
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reservations }
    end
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
    @reservation = Reservation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reservation }
    end
  end

  # GET /reservations/new
  # GET /reservations/new.json
  def new
    @reservation = Reservation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reservation }
    end
  end

  # GET /reservations/1/edit
  def edit
    @reservation = Reservation.find(params[:id])
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(params[:reservation])

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render json: @reservation, status: :created, location: @reservation }
      else
        format.html { render action: "new" }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reservations/1
  # PUT /reservations/1.json
  def update
    @reservation = Reservation.find(params[:id])

    respond_to do |format|
      if @reservation.update_attributes(params[:reservation])
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to reservations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def mobile_device?
    params[:m] == '1' || request.user_agent =~ /Mobile|webOS/
  end

end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper

  def base_rate(date = Date.today)
    if (Date.parse("December 16, 2022")..Date.parse("March 31, 2023")).include?(date)
      '375.00'
    else
      '325.00'
    end
  end

  def cleaning_fee
    '125.00'
  end

  def tax_rate
    0.175
  end

  def tax
    tax_rate * base_rate.to_f
  end

  def section_header(title)
    section_name = title.underscore.downcase
    content_tag(:div, class: 'section-wrap') do
      content_tag(:div, class: 'section') do
        content_tag(:div, class: 'wrapper') do
          concat link_to('', '#', {name: section_name})
          concat content_tag(:h3, title, id: section_name)
        end
      end
    end
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/contact/_form.html.erb
<%= form_for(@contact, remote: true, id: 'contact_form') do |f| %>
    <%= f.hidden_field(:device, value: mobile_device? ? 'mobile device' : 'desktop') %>
    <%= f.hidden_field(:device_type) %>
    <table class="basic w500">
      <tr>
        <td><%= f.label(:name) %></td>
        <td><%= f.text_field(:name, placeholder: 'Name') %></td>
      </tr>
      <tr>
        <td><%= f.label(:number_of_people) %></td>
        <td><%= f.text_field(:number_of_people, placeholder: 'Number of people') %></td>
      </tr>
      <tr>
        <td><%= f.label(:email) %></td>
        <td><%= f.text_field(:email, placeholder: 'Email') %></td>
      </tr>
      <tr>
        <td><%= f.label(:address) %></td>
        <td><%= f.text_field(:address, placeholder: 'Address') %></td>
      </tr>
      <tr>
        <td><%= f.label(:phone) %></td>
        <td><%= f.text_field(:phone, placeholder: 'Phone') %></td>
      </tr>
      <tr>
        <td><%= f.label(:arrival_date) %></td>
        <td><%= f.text_field(:arrival_date, placeholder: 'Arrival date', class: 'dp') %></td>
      </tr>
      <tr>
        <td><%= f.label(:departure_date) %></td>
        <td><%= f.text_field(:departure_date, placeholder: 'Departure date', class: 'dp') %></td>
      </tr>
      <tr>
        <td><%= f.label(:message) %></td>
        <td>
          <div>
            <%= f.text_area(:message, rows: 2, placeholder: 'Write a message') %>
          </div>
        </td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td><%= f.submit('Submit Inquiry', data: { disable_with: 'Submitting ..' }, style: "width: 88%;font-size:18px") %></td>
      </tr>
    </table>
<% end %>

app/views/contact/create.html.erb
<h1>Contact#create</h1>
<p>Find me in app/views/contact/create.html.erb</p>

app/views/home/_photos.html.erb
<ul id="myGallery">
  <% suffix = request.xhr? ? '_m' : '' %>
  <li><%= image_tag(asset_path("slides/mountain_view#{suffix}.jpg"), title: 'Mountain View from Yard') %></li>
  <li><%= image_tag(asset_path("slides/walking-up-front-deck#{suffix}.jpg"), title: "Walking up the front deck") %></li>
  <li><%= image_tag(asset_path("slides/dining-table#{suffix}.jpg"), title: "Dining Table") %></li>
  <li><%= image_tag(asset_path("slides/kitchen-island#{suffix}.jpg"), title: "Kitchen") %></li>
  <li><%= image_tag(asset_path("slides/living-room#{suffix}.jpg"), title: "Living Room") %></li>
  <li><%= image_tag(asset_path("slides/twin-bedroom#{suffix}.jpg"), title: "Second Bedroom (twins)") %></li>
  <li><%= image_tag(asset_path("slides/master-bedroom#{suffix}.jpg"), title: "Master Bedroom (queen)") %></li>
  <li><%= image_tag(asset_path("slides/bathroom#{suffix}.jpg"), title: "Cottage Bathroom") %></li>
  <li><%= image_tag(asset_path("slides/bathroom-window#{suffix}.jpg"), title: "Bathroom Window") %></li>
  <li><%= image_tag(asset_path("slides/shower#{suffix}.jpg"), title: "Walk-in Shower") %></li>
  <li><%= image_tag(asset_path("slides/back_yard#{suffix}.jpg"), title: "Backyard") %></li>
  <li><%= image_tag(asset_path("slides/front-deck#{suffix}.jpg"), title: "Front deck") %></li>
  <li><%= image_tag(asset_path("slides/view-from-deck#{suffix}.jpg"), title: "View from deck") %></li>
</ul>

app/views/home/index.html.erb
<%= content_tag(:div, '', id: 'front') unless mobile_device? %>
<%= hidden_field_tag(:base_rate, base_rate) %>
<%= hidden_field_tag(:tax_rate, tax_rate) %>
<%= hidden_field_tag(:main_pic_url, asset_path('front-deck-table-large.jpg')) %>
<div class="wrapper medium">
	<h2 class="c" style="margin-top: 0;">
		Welcome to Hana's Tradewind Cottage
	</h2>

	<p>
		As you follow the private drive through the tropical flower garden to our
		secluded Tradewinds Cottage, you will
		discover the Hawaii that you came to see.
	</p>
	<p>
    Surrounded by exotic flowers and tropical fruit trees, our two bedroom, one bath cottage has recently been beautifully remodeled. The kitchen features granite counter tops, a gas range, coffee maker and microwave. There is satellite TV, DVD player and WiFi.
  </p>
	<p>
    The cottage has a queen size bed in the master bedroom and two twin beds in the 2nd bedroom.
	</p>
</div>

<%= section_header('Reservations') %>

<div class="wrapper medium-minor mb20">
	<p class="medium">
		Planning a trip to the east side of Maui? Be sure to book your stay with us as early as possible.
		We are usually booked months in advance.
	</p>

	<h4>Rates</h4>
  <div class="pad medium-minor pad10">
    <table class="basic" cellpadding="0" cellspacing="0" border="0">
      <tr>
        <td>Base rate</td>
        <td>$<%= base_rate %><%= "*" if Date.today < Date.parse("December 16, 2022") %></td>
      </tr>
      <tr>
        <td><%= (tax_rate * 100).round(2) %>% tax</td>
        <td>+ $<%= tax.round(2) %></td>
      </tr>
      <tr>
        <td>Cleaning fee</td>
        <td>+ $<%= cleaning_fee %></td>
      </tr>
      <tr>
        <td>Total</td>
        <td style="border-top: 1px solid">$<%= (base_rate.to_f + cleaning_fee.to_f + tax).round(2) %></td>
      </tr>
    </table>
		<% if Date.today < Date.parse("December 16, 2022") %>
		  <p><b>*</b> The Winter Rate will be $375 a night, starting December 16th, 2022 until March 31st, 2023.</p>
    <% end %>
    <p>The cottage can accommodate a <b>maximum of 4</b> guests. <b>No pets.</b> If you have a service animal, please notify us ahead of time.</p>
  </div>

	<h4>Availability</h4>

	<p class="medium">
		Check availability for your trip at <a href="https://www.vrbo.com/293021" target="_blank">https://www.vrbo.com/293021</a>
  </p>
	<h4>Reservation Policies</h4>

	<ul class="pad medium-minor">
		<li>
			<b>Minimum stay:</b> We have a two night minimum stay.
		</li>

		<li>
			<b>Deposits:</b> A 25% deposit is required to reserve the cottage and the balance is due 30 days in advance.
		</li>

		<li style="margin-top: -15px;">
			<b>Payment:</b> We accept Visa, MasterCard, American Express and Discover.
			<span><%= image_tag(asset_path('visa_mastercard_american_express_discover.png'), style: 'position: relative;top: 13px;') %></span>
		</li>

		<li>
			<b>Check-in:</b> <br/>
			Check-in time is 3:00 p.m. <br/>
			Check-out time is 11:00 a.m.
		</li>

		<li>
			<b>Cancellation:</b>
			If you need to cancel, we will refund the amount that you paid <i>less</i> a <b>25% service fee</b>.
			Guests that check out prior to the registered check-out date will forfeit the balance of the payment. If
			anything is missing or damaged after you check out, we will charge your credit card for the cost of the
			repair and/or replacement of the item. Please let us know if there are any accidents or problems.
		</li>

		<li>
			<b>Laundry facilities:</b> Available free of charge for guests staying 5 or more nights.
		</li>

		<li>
			<b>Special Terms:</b>
			Rates and policies are subject to change.
			To provide a smoke free environment for our guests, smoking is only allowed outside.
			No pets are allowed at the cottage. If you have a licensed service dog please contact us ahead of time.
			<br/>

			<p><a href="#contact" class="linked scroll-to">Make a reservation inquiry.</a></p>
		</li>
	</ul>
</div>
<%= section_header('Photos') %>
<div class="wrapper medium-minor" id="photos_section">
	<% if mobile_device? %>
		<p>
			It looks like you're mobile, so we didn't load the pictures right
			away. <%= link_to('Load photos now!', 'javascript:;', class: 'linked', id: 'load_photos') %>
		</p>

		<div id="gallery_ph"></div>
	<% else %>
		<div id="gallery_container" style="height: 1155px;">
			<%= render('photos') %>
		</div>
	<% end %>
</div>
<%= section_header('Contact') %>
<div class="wrapper medium-minor">
	<div class="fl w49">
		<p class="form-text">
			Submit a reservation inquiry using the form below.
		</p>

		<div id="form_success_box" class="alert alert-info" style="display: none;">
			<b>Success!</b> We've received your inquiry and will get back to you at our earliest convenience.
		</div>
		<div id="form_error_box" class="alert alert-block alert-error fade" style="display: none;">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<h4 class="alert-heading">Oops!</h4>

			<p class="error-message"></p>
		</div>
		<div class="pad10 no-pad-mobile">
			<%= render('contact/form') %>
		</div>
	</div>
	<div class="fr w49">
		<p>
			Need help right away? Contact us directly.
		</p>

		<div class="pad10">
			<p class="medium">
				Phone: (808) 248-8980 <br/>
				Toll Free: 1-800-327-8097
			</p>

			<p class="medium">
				Email: <a href="mailto:brianna@tradewindscottage.net" class="linked">brianna@tradewindscottage.net</a>
			</p>
		</div>
		<div>
			<%= image_tag(asset_path('hamoa_overview.png'), width: '310') %>
		</div>
	</div>
  <div style="clear:both"></div>
</div>
<%= section_header('Hana') %>
<div class="wrapper medium-minor">
	<p class="medium">
		Hana is a small town located on the <b>east side of Maui</b>. It is home to some of the
		<a href="http://xfinity.comcast.net/slideshow/news-bestbeaches/7/" target="_blank" class="linked">
			world’s most beautiful beaches</a>,
		breath taking waterfalls, and majestic coastlines. From Kahului airport it is about a 50 mile drive along the
		winding coastline. Along the way you can enjoy hiking trails, beautiful overlooks, and incredible waterfalls.
	</p>

	<p>
		Hana town is limited when it comes to night life and dining options. There is one gas station and two small
		stores (<b>closes at 7:30 PM</b>). If you are staying for several nights, we recommend buying groceries in
		Kahului
		before driving to Hana. Travaasa Hotel has a bar and restaurant, although it is a bit pricey, and so does
		the Hana Ranch Restaurant (also pricey). There are a several locally owned eateries and lunch
		wagons around town. A local favorite is
		<a href="http://www.yelp.com/biz/thai-food-by-pranee-hana" target="_blank" class="linked" title="view Pranee's on Yelp">Pranee's</a>,
		which has excellent Thai food. Checkout
		<a href="http://www.yelp.com/search?find_desc=&find_loc=H%C4%81na%2C+HI&ns=1&ls=2b7c66da1def68e9" target="_blank" class="linked">Hana
			on Yelp</a>
		for a list of popular activities and food options.
	</p>

	<p>
		There are a variety of outdoor activities, some of which we’ve listed below. It is nice to have a couple of
		days to
		spend in Hana because it is a long trip out here. That way you have some time to just relax and explore this
		side of
		the island.
	</p>

	<p>
		For more information on Hana please visit
		<a target="_blank" href="http://www.hanamaui.com" class="linked">hanamaui.com</a>
	</p>
	<h4>Activities</h4>
	<ul class="pad">
		<li>Go hang gliding down the road (1 minute away):
			<a target="_blank" href="http://www.hangglidingmaui.com" class="linked">hangglidingmaui.com</a></li>
		<li>Spelunking in lava tube (2 minutes away):
			<a target="_blank" href="http://www.mauicave.com" class="linked">mauicave.com</a>
		</li>
		<li>Guided hike and taro patch tour at Kapahu Living Farm (45 minutes away):
			<a target="_blank" href="http://kipahulu.org/hike.html" class="linked">kipahulu.org/hike.html</a></li>
		<li>Ohe’o (7 Sacred Pools) and bamboo forest (45 minutes away):
			<a target="_blank" href="http://www.nps.gov/hale/index.htm" class="linked">nps.gov/hale/</a></li>
	</ul>
	<h4>Location</h4>

	<p>The map below shows the route from the Kahului Airport (OGG) to the Tradewind Cottage (Approximately 52
		miles).</p>
	<% unless Rails.env.development? %>
		<iframe src="https://www.google.com/maps/embed?pb=!1m29!1m12!1m3!1d238610.7238657256!2d-156.3722470141209!3d20.860254975716938!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m14!1i0!3e6!4m5!1s0x7954d2b01b8e0419%3A0xc35ea962dd1a9041!2sKahului+Airport%2C+1+Kahului+Airport+Rd%2C+Kahului%2C+HI+96732!3m2!1d20.896791999999998!2d-156.43293799999998!4m5!1s0x7954ada37cc29da1%3A0xb9089f2ff788b1df!2sHana&#39;s+Tradewind+Cottages%2C+135+Alalele+Rd%2C+Hana%2C+HI+96713!3m2!1d20.790406!2d-156.01775899999998!5e0!3m2!1sen!2sus!4v1394938868443" width="100%" height="450" frameborder="0" style="border:0"></iframe>
	<% end %>
</div>

app/views/inquiry/new_inquiry.text.erb
Hey Bri,

You got a new reservation inquiry from tradewindscottage.net!

Reservation info:

    Name: <%= @contact.name || '[n/a]' %>
    Number of people: <%= @contact.number_of_people || '[n/a]' %>
    Email: <%= @contact.email || '[n/a]' %>
    Address: <%= @contact.address || '[n/a]' %>
    Phone: <%= @contact.phone || '[n/a]' %>
    Duration: <%= pluralize(@date_range.diff_days, "Night") rescue 'error' %>
    Arrival Date: <%= @contact.arrival_date.try(:strftime, '%m/%d/%Y') || '[n/a]' %>
    Departure Date: <%= @contact.departure_date.try(:strftime, '%m/%d/%Y') || '[n/a]' %>
    Message: <%= @contact.message_for_email %>

Have a great day!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Hana's Tradewind Cottage</title>
  <%= stylesheet_link_tag('application', media: 'all') %>
  <%= stylesheet_link_tag('mobile') if mobile_device? %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag('favicon.ico') %>
  <meta name="google-site-verification" content="KDeQ0u-a5jxWH8XmJ5lRCxij-xzkkwrpYhQ8rtAXEbM"/>
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-37742500-1']);
      _gaq.push(['_trackPageview']);

      (function () {
          var ga = document.createElement('script');
          ga.type = 'text/javascript';
          ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0];
          s.parentNode.insertBefore(ga, s);
      })();

  </script>
</head>
<body>
<div class="row">
  <header id="nav_bar">
    <div class="wrapper nav">
      <div id="logo" class="deep-text">
        <h1><span class="hidden-mobile">Hana's</span> Tradewind Cottage</h1>
      </div>
      <ul id="page_nav">
        <li>
          <a href="#reservations" class="scroll-to">Reservations</a>
        </li>
        <li>
          <a href="#photos" class="scroll-to">Photos</a>
        </li>
        <li>
          <a href="#contact" class="scroll-to">Contact</a>
        </li>
        <li>
          <a href="#hana" class="scroll-to">Hana</a>
        </li>
      </ul>
    </div>
  </header>
</div>

<div id="container">
  <div id="content">
    <a name="#top"></a>
    <%= yield %>
  </div>
</div>
<footer>
  <div class="wrapper">
    <span>Hana's Tradewind Cottage</span>
    &#8226;
    <span>(808) 248-8980</span>
    &#8226;
    <span>County permit # STHA 2018/0001, SUP2 2012/0034</span>
    &#8226;
    <span>Hawaii State Tax ID #134-723-3792-01</span>
  </div>
</footer>
<%= javascript_include_tag 'application' %>
<script type="text/javascript">
    $(function () {

        $('#logo h1').bind('click', function () {
            window.location.hash = '#top';
        });

    });
</script>
</body>
</html>

app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<h1>Listing reservations</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reservations.each do |reservation| %>
  <tr>
    <td><%= reservation.name %></td>
    <td><%= link_to 'Show', reservation %></td>
    <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
    <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New reservation</h1>

<%= render 'form' %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @reservation.name %>
</p>


<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>